config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ('/')
  # root 'posts#index'
  root 'home#home'

  get '/home', controller: 'home', action: 'home', as: 'home'
  resources :posts, only: %i[index new create]
  resources :friends, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(id: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = "Post was successfully created." }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :author, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.haml
.bg-blue-500.text-white.flex.justify-center.items-center.w-full{ class: 'h-1/12', data: { controller: 'headers' } }
  = link_to 'Homepage', root_path, class: 'navlink hover:underline m-5', data: { 'turbo-frame': 'frame_1', 'headers-target': 'home', action: 'click->headers#chooseLink'}
  = link_to 'Posts', posts_path, class: 'navlink hover:underline m-5', data: { 'turbo-frame': 'frame_1', 'headers-target': 'posts', action: 'click->headers#chooseLink'}
  = link_to 'Friends', friends_path, class: 'navlink hover:underline m-5', data: { 'turbo-frame': 'frame_1', 'headers-target': 'friends', action: 'click->headers#chooseLink'}

app/views/friends/index.html.haml
= turbo_frame_tag 'frame_1', data: { turbo_action: :replace } do
  .font-bold.text-2xl= 'Friends'
  .mt-12.italic= 'Here we will create many different posts to play with turbo_stream and other concepts'

app/views/home/home.html.haml
= turbo_frame_tag 'frame_1', data: { turbo_action: :replace } do
  .font-bold.text-2xl= 'Home'
  .mt-12.italic= 'Welcome to our website! Here you will learn everything about the Hotwire library!'

app/views/layouts/_flash.html.haml
- flash.each do |flash_type, message|
  .flash.text-lg.py-2.px-8.rounded-3xl{ data: { controller: "flashes", action: "animationend->removals#remove" }, class: flash_type.to_s }
    = message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TurboPlayground
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body{ class: 'h-11/12' }
    = render 'application/header'
    #flash= render "layouts/flash"
    %main.container.mx-auto.mt-28.px-5.flex.w-full.h-full
      .flex.flex-col.w-full.h-full
        .font-bold.text-2xl= 'Frame number One [turbo_action: :replace]'
        .border-2.rounded-xl.border-green-500.w-full.h-full.flex.flex-col.p-4
          = yield

app/views/posts/_form.html.haml
= form_for @post, html: { class: 'p-4 flex flex-col', style: 'width: 40rem;' }, data: { turbo_frame: "new_post" } do |form|
  .w-full.flex.items-center.justify-between.my-2
    = form.text_field :title, placeholder: 'Title', class: 'w-1/3'
    = form.text_field :author, placeholder: 'Author', class: 'w-1/3'
  = form.text_area :content, placeholder: 'Lorem ipsum dolor sit amet...', class: 'w-full'
  .w-full.flex.justify-center.my-2
    = form.submit 'Submit', class: 'bg-blue-700 hover:bg-blue-500 text-white rounded-xl p-4'

app/views/posts/_post.html.haml
.w-full.flex.flex-col.shadow-xl.rounded-xl.bg-gray-200.p-4.my-2
  .w-full.flex.items-center.justify-between
    .font-bold.text-lg= post.title
    .font-bold.text-base.italic= "by: #{post.author}"
  .w-full.text-base= post.content

app/views/posts/_presentation.html.haml
.w-full.flex.flex-col.items-center
  .w-full.flex.justify-between.items-center
    .font-bold.text-2xl= 'Posts'
    = link_to 'New Post', new_post_path, class: 'bg-blue-700 hover:bg-blue-500 rounded-xl shadow p-4 text-white', data: {turbo_frame: :new_post}
  .mt-12.italic= 'Here we will create many different posts to play with other turbo_actions'

app/views/posts/create.turbo_stream.haml
= turbo_stream.prepend 'posts', partial: 'posts/post', locals: { post: @post }
= turbo_stream.prepend "flash", partial: "layouts/flash"
= turbo_stream.replace "new_post", partial: "posts/presentation"

app/views/posts/index.html.haml
= turbo_frame_tag 'frame_1', data: { turbo_action: :replace } do
  .mt-4.font-bold.text-xl= 'Frame para Form (turbo_action: :replace)'
  .w-full.border-blue-500.border-2.flex.flex-row.rounded-xl.mt-4.justify-center
    = turbo_frame_tag 'new_post', data: { class: 'w-full', turbo_action: :replace } do
      = render 'presentation'
  .mt-4.font-bold.text-xl= 'Frame para Posts (turbo_action: :prepend)'
  .w-full.border-yellow-500.border-2.flex.flex-col.rounded-xl.mt-4.p-2
    = link_to 'Reload', posts_path, class: 'text-gray-500 hover:underline', data: { turbo_frame: :posts }
    = turbo_frame_tag 'posts', data: { turbo_action: :prepend } do
      - if @posts.present?
        - @posts.each do |post|
          = render 'post', post:
      - else
        .w-full.text-center= 'There are no posts'

app/views/posts/new.html.haml
= turbo_frame_tag 'new_post', data: { turbo_action: :replace } do
  .w-full
    = link_to 'Back', posts_path, class: 'text-gray-500 hover:underline', data: { turbo_frame: "new_post" }
  = render 'form'